# -------------------------------------
# -------------------------------------
# è¿™ä¸ªæ–‡ä»¶æ²¡ä»€ä¹ˆç”¨,ä½†æ˜¯åˆ äº†åˆæ²¡æ³•è·‘???
# æ²¡æ€Žä¹ˆçœ‹å¼€å‘æ–‡æ¡£,æ‰€ä»¥ä¸çŸ¥é“æ€Žä¹ˆè§£å†³
# æœ¬æ¥æ˜¯å¯ä»¥æ²¡æœ‰çš„æˆ‘ä¹Ÿä¸æ‰“ç®—åšä½†æ˜¯ä¸ºäº†config.ymlæ˜¾å¾—ä¸æ˜¯é‚£ä¹ˆæ²¡ç”¨æ‰€ä»¥åŠ äº†å¤šè¯­è¨€
# ðŸ¦
# -------------------------------------
# -------------------------------------

# ä½¿ç”¨çš„è¯­è¨€,å¦‚æžœä¸è‡ªå·±åŠ çš„è¯æ”¯æŒcnä¸Žen.é…ç½®æ–‡ä»¶ä½äºŽ./lang
language: "cn"

# æ’ä»¶å‘é€çš„æ¶ˆæ¯å‰ç¼€
prefix: "&bCDKer &7> &f"